baseURL = ""
languageCode = "es-es"
title = "Ciudad Real Tech Hub"
theme = "ananke"

DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

#[languages]
#  [languages.es]
#    title = "Ciudad Real Tech Hub"
#    weight = 1
#    contentDir = "content"
#  [languages.en]
#    title = "Ciudad Real Tech Hub"
#    weight = 2
#    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = "/images/crth-100.png"
  description = "Ciudad Real Technology Hub, la agrupación de asociaciones tecnológicas de la provincia."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = "https://ciudadrealtechhub.herokuapp.com/"
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page:
  # http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/tech-bg.jpg"
  recent_posts_number = 2

[menu]
[[menu.main]]
  identifier = 'About'
  name = 'About CRTH'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = -110

[[menu.main]]
  identifier = 'meetings-agilecr'
  name = 'Meetings Agile-CR'
  pre = "<i class='fa fa-heart'></i>"
  url = '/meetings-agilecr/'
  weight = -110
