baseURL = ""
languageCode = "es-es"
title = "Ciudad Real Tech Hub"
theme = "ananke"

DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = "/images/crth-100.png"
  description = "Ciudad Real Technology Hub, la agrupación de asociaciones tecnológicas de la provincia."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = "https://ciudadrealtechhub.herokuapp.com/"
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page:
  # http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/tech-bg.jpg"
  recent_posts_number = 2
  mainSections = ["posts"]

[menu]
[[menu.main]]
  identifier = 'about'
  name = 'About CRTH'
  url = '/about/'
  weight = 0

[[menu.main]]
  identifier = 'posts'
  name = 'Posts'
  url = '/posts/'
  weight = 1

[[menu.main]]
  identifier = 'grupos'
  name = 'Grupos'
  url = '/grupos/'
  weight = 2

